default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: qiita2_development

test:
  <<: *default
  database: qiita2_test

production:
  url: <%= ENV['DATABASE_URL'] %>
